### ISSUE TITLE
Issue in termux

### ISSUE THREAD

**Issue by ArunDinfinity** [CyberSaxosTiGER/pervertgram#1]
python3 app.py                                Fail to import moviepy. Need only for Video upload.                                             Request return 429 error!                       {'message': 'Please wait a few minutes before you try again.', 'status': 'fail'}                Request return 404 error!                       Login success!                                                                                   * Serving Flask app "app" (lazy loading)        * Environment: production                         WARNING: Do not use the development server in a production environment.                         Use a production WSGI server instead.         * Debug mode: on                                * Running on http://127.0.0.1:5002/ (Press CTRL+C to quit)                                      * Restarting with stat                         Traceback (most recent call last):                File "app.py", line 108, in <module>              app.run(host="127.0.0.1", port='5002', debug=True)                                            File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 943, in run                                                 run_simple(host, port, self, **options)       File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/werkzeug/serving.py", line 1007, in run_simple                                  run_with_reloader(inner, extra_files, reloader_interval, reloader_type)                       File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader                          sys.exit(reloader.restart_with_reloader())    File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader                      exit_code = subprocess.call(args, env=new_environ, close_fds=False)                           File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 323, in call             with Popen(*popenargs, **kwargs) as p:        File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 775, in __init__         restore_signals, start_new_session)           File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 1520, in _execute_child                                                  raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/data/data/com.termux/files/home/pervertgram/app.py'

**Comment by ArunDinfinity** [comment]
Fixed by adding shebang statement for app.py
nano app.py
Add the following line at first
#!/usr/bin/env python
